version: 1.31.Final.{build}
image: Visual Studio 2019
clone_folder: c:\project\mediaportal
environment:
  JAVA_HOME: C:\Program Files (x86)\Java\jdk1.8.0
install:
- cmd: >-
    git submodule update --init --recursive

    choco install nsis --version=3.08

    java -version
build_script:
- cmd: >-
    cd c:\project\mediaportal\build\

    BuildFullinstaller.cmd

    7z a ..\Release\MediaPortalSetup_%APPVEYOR_BUILD_VERSION%.%APPVEYOR_REPO_COMMIT%.zip ..\Release\MediaPortalSetup_*.exe

    7z a BuildFullInstaller.zip BuildFullInstaller.log
test: off
artifacts:
- path: Release\MediaPortalSetup_*.zip
  name: Mediaportal Installer (Zip)
- path: Build\BuildFullInstaller.zip
  name: Mediaportal Build Log
on_failure:
- ps: Push-AppveyorArtifact BuildFullInstaller.log -FileName BuildError.log
