name: Mediaportal / Release

on:
  # On Push Release Tag
  push:
   tags:
      - "Release_*"

jobs:
  build:
    uses: ./.github/workflows/mediaportal.yml
  
  release:
    name: Release Mediaportal
    needs: build
    permissions:
      contents: write
    
    runs-on: windows-2019
    
    steps:
      - name: Download х86 Artifacts 
        uses: actions/download-artifact@v3
        with:
          name: Mediaportal setup file x86
          path: release-files

      - name: Download х64 Artifacts 
        uses: actions/download-artifact@v3
        with:
          name: Mediaportal setup file x64
          path: release-files

      - name: 7z Artifacts
        run: |
          FOR %%I IN (*.exe) DO 7z.exe a -tZip "%%~nI.zip" "%%~I"
        shell: cmd
        working-directory: release-files

      - name: Check artifacts
        run: |
          dir /S
        shell: cmd
        working-directory: release-files

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release-files/MediaPortalSetup_*.zip
